language: nix
nix: 2.2.1
git:
  submodules_depth: 2

script: |
  (
  set -euxo pipefail

  # print something so Travis doesn't kill us
  while sleep 5m; do echo "=====[ $SECONDS seconds, nix still building... ]====="; done &

  # load the cache
  nix-env -iA cachix -f https://cachix.org/api/v1/install
  cachix use cross-armed

  # login if we have permission
  if [[ ${CACHIX_AUTH_TOKEN:-} ]]; then
    cachix authtoken "$CACHIX_AUTH_TOKEN"
  fi

  # build an rpi0 sample image
  nix-build . \
    --cores 2 \
    --max-jobs 2 \
    --no-build-output \
    -I nixpkgs=nixpkgs \
    -I machine=machines/raspberrypi-zerow \
    -I image=images/rpi0-otg-ether

  # push rpi0 with permission
  if [[ ${CACHIX_AUTH_TOKEN:-} ]]; then
    cachix push cross-armed $(readlink -f result)
    cachix push cross-armed $(nix-store -qd result)
  fi

  # build a beaglebone sample image
  nix-build . \
    --cores 2 \
    --max-jobs 2 \
    --no-build-output \
    -I nixpkgs=nixpkgs \
    -I machine=machines/beaglebone \
    -I image=images/minimal

  # push beaglebone with permission
  if [[ ${CACHIX_AUTH_TOKEN:-} ]]; then
    cachix push cross-armed $(readlink -f result)
    cachix push cross-armed $(nix-store -qd result)
  fi

  # build a toradex apalis imx6 sample image
  nix-build . \
    --cores 2 \
    --max-jobs 2 \
    --no-build-output \
    -I nixpkgs=nixpkgs \
    -I machine=machines/toradex_apalis_imx6 \
    -I image=images/minimal

  # push toradex apalis imx6 with permission
  if [[ ${CACHIX_AUTH_TOKEN:-} ]]; then
    cachix push cross-armed $(readlink -f result)
    cachix push cross-armed $(nix-store -qd result)
  fi

  # kill the background process
  kill %1
  )
